name: Blank workflow

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set Version name in variable
      run: |
        @echo on
        for /F "tokens=*" %i IN ('git describe --tags') DO SET version=%i
        echo  %version%


    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps.version.outputs) }}
      run: echo %STEPS_CONTEXT%
